name: bospace
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python = 3.10
  - numpy
  - pytorch
  - cudatoolkit=11.8
  - pip
  - transformers
  - datasets
  - dataclasses
  - scipy
  - scikit-learn
  - python-dotenv
  - pip: 
      - gpytorch
      - botorch
      - fastapi
